public extension Highlightr {
	enum SupportedLanguage: String, CaseIterable {
		case lang1c = "1c"
		case abnf
		case accesslog
		case actionscript
		case ada
		case angelscript
		case apache
		case applescript
		case arcade
		case arduino
		case armasm
		case asciidoc
		case aspectj
		case autohotkey
		case autoit
		case avrasm
		case awk
		case axapta
		case bash
		case basic
		case bnf
		case brainfuck
		case cal
		case capnproto
		case ceylon
		case clean
		case clojure
		case clojureRepl = "clojure-repl"
		case cmake
		case coffeescript
		case coq
		case cos
		case cpp
		case crmsh
		case crystal
		case cs
		case csp
		case css
		case d
		case dart
		case delphi
		case diff
		case django
		case dns
		case dockerfile
		case dos
		case dsconfig
		case dts
		case dust
		case ebnf
		case elixir
		case elm
		case erb
		case erlang
		case erlangRepl = "erlang-repl"
		case excel
		case fix
		case flix
		case fortran
		case fsharp
		case gams
		case gauss
		case gcode
		case gherkin
		case glsl
		case gml
		case go
		case golo
		case gradle
		case groovy
		case haml
		case handlebars
		case haskell
		case haxe
		case hsp
		case htmlbars
		case http
		case hy
		case inform7
		case ini
		case irpf90
		case isbl
		case java
		case javascript
		case jbossCli = "jboss-cli"
		case json
		case julia
		case juliaRepl = "julia-repl"
		case kotlin
		case lasso
		case ldif
		case leaf
		case less
		case lisp
		case livecodeserver
		case livescript
		case llvm
		case lsl
		case lua
		case makefile
		case markdown
		case mathematica
		case matlab
		case maxima
		case mel
		case mercury
		case mipsasm
		case mizar
		case mojolicious
		case monkey
		case moonscript
		case n1ql
		case nginx
		case nimrod
		case nix
		case nsis
		case objectivec
		case ocaml
		case openscad
		case oxygene
		case parser3
		case perl
		case pf
		case pgsql
		case php
		case plaintext
		case pony
		case powershell
		case processing
		case profile
		case prolog
		case properties
		case protobuf
		case puppet
		case purebasic
		case python
		case q
		case qml
		case r
		case reasonml
		case rib
		case roboconf
		case routeros
		case rsl
		case ruby
		case ruleslanguage
		case rust
		case sas
		case scala
		case scheme
		case scilab
		case scss
		case shell
		case smali
		case smalltalk
		case sml
		case sqf
		case sql
		case stan
		case stata
		case step21
		case stylus
		case subunit
		case swift
		case taggerscript
		case tap
		case tcl
		case tex
		case thrift
		case tp
		case twig
		case typescript
		case vala
		case vbnet
		case vbscript
		case vbscriptHtml = "vbscript-html"
		case verilog
		case vhdl
		case vim
		case x86asm
		case xl
		case xml
		case xquery
		case yaml
		case zephir
	}
}